<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BioTrace.Elsa.Abp.Studio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BioTrace.Elsa.Abp.Studio.BlazorWasm\BioTrace.Elsa.Abp.Studio.BlazorWasm.csproj" />
    <ProjectReference Include="..\BioTrace.Elsa.Abp.Studio.Client\BioTrace.Elsa.Abp.Studio.Client.csproj" />
  </ItemGroup>

</Project>
