<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>BioTrace.Elsa.Abp</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.4.0"/>
    <ProjectReference Include="..\BioTrace.Elsa.Abp.Domain.Shared\BioTrace.Elsa.Abp.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
