<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>BioTrace.Elsa.Abp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BioTrace.Elsa.Abp.Application\BioTrace.Elsa.Abp.Application.csproj" />
    <ProjectReference Include="..\BioTrace.Elsa.Abp.Domain.Tests\BioTrace.Elsa.Abp.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
