services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/BioTrace.Elsa.Abp:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
