CREATE DATABASE "BioTrace_Abp";
CREATE DATABASE "BioTrace_Elsa";
CREATE DATABASE "BioTrace_Abp_Test";
CREATE DATABASE "BioTrace_Elsa_Test";
CREATE DATABASE "BioTrace_Abp_E2E";
CREATE DATABASE "BioTrace_Elsa_E2E";
