<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BioTrace.Elsa.Abp</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Api.Client" Version="$(ElsaPackageVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <ProjectReference Include="..\BioTrace.Elsa.Abp.IntegrationTesting\BioTrace.Elsa.Abp.IntegrationTesting.csproj" />
    <ProjectReference Include="..\..\host\BioTrace.Elsa.Abp.HttpApi.Host\BioTrace.Elsa.Abp.HttpApi.Host.csproj" />
  </ItemGroup>

</Project>
